require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - app/chewy/*
    - config/**/*
    - db/**/*
    - lib/tasks/*
    - Guardfile
    - Capfile
    - Gemfile
    - Rakefile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/support/*
    - spec/factories/*
    - bin/*
    - node_modules/**/*
    - public/packs/**/*
    - public/packs-test/**/*
    - lib/named_logger.rb
    - lib/active_cacher.rb
    - lib/dsl_attribute.rb
  UseCache: false
  NewCops: enable

Layout/LineLength:
  Max: 100
  AllowURI: true
  IgnoreCopDirectives: true
  AllowedPatterns: ['\A\ *#']
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
  AllowedMethods:
    - state_machine
Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*
Style/WordArray:
  Exclude:
    - spec/**/*
Style/NumericLiterals:
  Exclude:
    - spec/**/*
Security/Open:
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15

Migration/DepartmentName:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/Delegate:
  EnforceForPrefixed: false

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
Style/StringLiteralsInInterpolation:
  Description: Checks if uses of quotes inside expressions in interpolated strings
    match the configured preference.
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Layout/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
  - leading
  - trailing

Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/CollectionMethods:
  Description: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find_all: select
    reduce: inject
    detect: find

Style/Lambda:
  EnforcedStyle: literal

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
