class Studio < ActiveRecord::Base
  Merged = {
    83 => 48,
    88 => 48,
    292 => 48,
    425 => 48,
    436 => 48,
    805 => 48,
    141 => 18
  }

  validates :image, attachment_content_type: { content_type: /\Aimage/ }

  # Relations
  has_and_belongs_to_many :animes
  has_attached_file :image,
    url: "/images/studio/:style/:id.:extension",
    path: ":rails_root/public/images/studio/:style/:id.:extension"

  @@studio_name_filter = /°|^studios? | studios?$| productions?$| entertainment?$| animation?$|^animation? /i

  def self.filtered_name name
    #name.downcase.gsub(@@studio_name_filter, '')
    name.gsub(@@studio_name_filter, '')
  end

  def filtered_name
    Studio.filtered_name name
  end

  # создающая ли это аниме студия или просто продюссер
  def real?
    @@real_studios.include?(self.class.filtered_name(self.name).downcase)
  end

  # возвращет настоящую струдию, если это была склеенная студия
  def real
    Merged.keys.include?(self.id) ? self.class.find(Merged[self.id]) : self
  end

  # возвращет все id, связанные с текущим
  def self.related(id)
    Merged.map { |k,v| k == id ? v : (v == id ? k : nil) }.compact << id
  end

  # возвращает все аниме студии с учетом склеенных студий
  def all_animes
    self.animes unless Merged.values.include?(self.id)
    ids = []
    ActiveRecord::Base.connection
        .execute('SELECT * FROM animes_studios where studio_id in (%s)' % (Merged.select {|k,v| v == self.id }.map {|k,v| k } + [self.id]).join(',')).each do |v|
      ids << v[0]
    end
    Anime.where(id: ids)
  end

  def to_param
    "%d-%s" % [id, name.gsub(/[^\w]+/, '-').gsub(/^-|-$/, '')]
  end

  @@real_studios = [
    "artland",
    "actas",
    "studio hibari",
    "studio rikka",
    "ufotable",
    "hal film maker",
    "synergysp",
    "production i.g",
    "brains base",
    "daume",
    "comix wave",
    "white fox",
    "ob planning",
    "manglobe",
    "arms",
    "studio gallop",
    "satelight",
    "aic",
    #"warner bros. animation",
    "a.c.g.t.",
    "appp",
    "feel.",
    'silver link',
    "tyo animations",
    "madhouse",
    "madhouse studios",

    # с википедии
    "a-1 pictures inc.",
    "a.c.g.t",
    "actas inc.",
    "anime international company inc.",
    "arms corporation",
    "artland, inc.",
    "asahi production",
    "bee train production inc.",
    "bones",
    "brain's base",
    "daume",
    "david production",
    "dax international",
    "diomedea",
    "dogakobo",
    "eight bit",
    "eiken",
    "feel",
    "gainax",
    "gallop",
    "gonzo",
    "gohands",
    "group tac",
    "hal film maker",
    "imagin",
    "j.c.staff",
    "kyoto animation",
    "magic bus",
    "manglobe",
    "mook animation",
    "mushi production",
    "nippon animation",
    "fifth avenue",
    "nomad",
    "olm",
    "ordet",
    "p.a. works",
    "pierrot",
    "pierrot plus",
    "production i.g",
    "satelight",
    "shaft",
    "shin-ei animation",
    "studio 4°c",
    "studio comet",
    "studio deen",
    "studio fantasia",
    "studio ghibli",
    "studio hibari",
    "studio nue",
    "studio gokumi",
    "sunrise",
    "synergysp",
    "tatsunoko production",
    "tezuka production",
    "tms entertainment",
    "tnk",
    "toei animation",
    "triangle staff",
    "ufotable",
    "white fox",
    "xebec",
    "zexcs",
    "a. film",
    "aardman animations",
    "act3animation",
    "akom",
    "anima studios",
    "animafilm",
    "animal logic",
    "animation collective",
    "animax entertainment",
    "anzovin studio",
    "asterisk animation",
    "atomic cartoons",
    "bardel entertainment",
    "bee train",
    "bent image lab",
    "big idea productions",
    "bird studios",
    "blue sky studios",
    "blue-zoo",
    "bolexbrothers",
    "bones",
    "brb international",
    "brown bag films",
    "cartoon pizza/jumbo pictures",
    "cartoon network studios",
    "cartoon saloon",
    "cammot",
    "clockwork zoo animation",
    "collingwood o'hare entertainment",
    "cookie jar group",
    "cosgrove hall films",
    "cosmic toast studios",
    "crest animation studios",
    "cuckoo's nest studio",
    "def2shoot",
    "disneytoon studios",
    "dreamworks animation",
    "dr movie",
    "dong woo animation",
    "eiken",
    "fatkat",
    "filmfair",
    "film roman, inc.",
    "fine arts films",
    "folimage",
    "fox animation studios",
    "frederator studios",
    "future thought productions",
    "gainax",
    "global mechanic",
    "gonzo",
    "group tac",
    "guru studios",
    "h5",
    "highlander productions",
    "hong ying animation",
    "hoods entertainment",
    "ilion animation studios",
    "illumination entertainment",
    "imagi animation studios",
    "j.c. staff",
    "jetix animation concepts",
    "jibjab",
    "kandor graphics",
    "klasky csupo",
    "koko enterprises",
    "kyoto animation",
    "laika",
    "les' copaque production",
    "littlenobody",
    "linterna magica studio",
    "lucasfilm animation",
    "mac guff",
    "march entertainment",
    #"marvel animation",
    "mappa",
    "marwah films & video studios",
    "melnitsa animation studio",
    "metro-goldwyn-mayer animation",
    "mike young productions",
    "mirari films",
    "national film board of canada",
    "naz",
    "nelvana",
    "nickelodeon animation studios",
    "nippon animation",
    "pacific data images",
    "pannóniafilm",
    "pentamedia graphics",
    "the people's republic of animation",
    "pixar",
    "plus one animation",
    "post amazers",
    "powerhouse animation studios, inc.",
    "production i.g",
    "production reed",
    "p.a. works",
    "radicial axis",
    "rainmaker digital effects",
    "renegade animation",
    "rubicon group holding",
    "rhythm and hues studios",
    "rough draft studios",
    "saerom",
    "se-ma-for",
    "six point harness",
    "skycron",
    "smallfilms",
    "šaf",
    "shaft",
    "sony pictures animation",
    "soup2nuts",
    "soyuzmultfilm",
    "sparx*",
    "spectrum animation",
    "spümcø",
    "spy pictures",
    "start anima",
    "starz animation",
    "stretch films",
    "studio 3hz",
    "studio 4°c",
    "studio b",
    "studio comet",
    "studio deen",
    "studio gallop",
    "studio ghibli",
    "studio pierrot",
    "sumo dojo",
    "sunrise",
    "sunwoo entertainment",
    "tatsunoko productions",
    "titmouse",
    "toei animation",
    "teletoon canada",
    "tms",
    "toon city",
    "toonz",
    "trigger",
    "palm studio",
    "universal animation studios",
    "walsh family media",
    "walt disney animation studios",
    "walt disney television animation",
    "wang film productions",
    "w!ldbrain",
    "williams street studios",
    "wit studio",
    "xebec",
    "xilam",
    "xyzoo animation",
    "zagreb school of animated films",
  ].map {|v| v.gsub(@@studio_name_filter, '') }
end
