class UserHistoryAction
  Add = 'add'
  Delete = 'delete'
  Status = 'status'
  CompleteWithScore = 'complete_with_score'
  Episodes = 'episodes'
  Volumes = 'volumes'
  Chapters = 'chapters'
  Rate = 'rate'
  MalAnimeImport = 'mal_anime_import'
  MalMangaImport = 'mal_manga_import'
  ApAnimeImport = 'ap_anime_import'
  ApMangaImport = 'ap_manga_import'
  AnimeImport = 'anime_import'
  MangaImport = 'manga_import'
  Registration = 'registration'
  AnimeHistoryClear = 'anime_history_clear'
  MangaHistoryClear = 'manga_history_clear'
end
