class UserHistoryAction
  ADD = 'add'
  DELETE = 'delete'
  STATUS = 'status'
  COMPLETE_WITH_SCORE = 'complete_with_score'
  EPISODES = 'episodes'
  VOLUMES = 'volumes'
  CHAPTERS = 'chapters'
  RATE = 'rate'
  MAL_ANIME_IMPORT = 'mal_anime_import'
  MAL_MANGA_IMPORT = 'mal_manga_import'
  AP_ANIME_IMPORT = 'ap_anime_import'
  AP_MANGA_IMPORT = 'ap_manga_import'
  ANIME_IMPORT = 'anime_import'
  MANGA_IMPORT = 'manga_import'
  REGISTRATION = 'registration'
  ANIME_HISTORY_CLEAR = 'anime_history_clear'
  MANGA_HISTORY_CLEAR = 'manga_history_clear'
end
