name: Prepare RSpec Docker image

on:
  push:
    paths:
      - 'config/rspec/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    defaults:
      run:
        working-directory: './config/rspec/v1.0.0'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build'
        run: |
          docker build . --tag ghcr.io/shikimori/rspec:v1.0.0
          docker push ghcr.io/shikimori/rspec:v1.0.0